Product:
    type: entity
    table: product
    uniqueConstraints:
        productBundleId:
            columns:
                - bundleId
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        duration:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        bundleid:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            column: bundleId
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        consumable:
            type: boolean
            nullable: false
            comment: ''
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
        weight:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
        available:
            type: boolean
            nullable: false
            comment: ''
            options:
                default: '0'
        vat:
            type: float
            nullable: false
            precision: 10
            scale: 0
            comment: ''
    oneToMany:
        purchasedProducts:
            targetEntity: Core\Model\PurchasedProduct
            mappedBy: product
        productFunctionalities:
            targetEntity: Core\Model\ProductFunctionality
            mappedBy: product