<?php


$applicationContext = \Core\Context\ApplicationContext::getInstance();
$errorManager = $applicationContext->getErrorManager();

defined('ERROR_INTERNAL_ERROR') || define('ERROR_INTERNAL_ERROR', 1);
$errorManager->defineError('ERROR_INTERNAL_ERROR');

defined('ERROR_REQUEST_INVALID') || define('ERROR_REQUEST_INVALID', 2);
$errorManager->defineError('ERROR_REQUEST_INVALID');

defined('ERROR_SERVICE_NOT_FOUND') || define('ERROR_SERVICE_NOT_FOUND', 3);
$errorManager->defineError('ERROR_SERVICE_NOT_FOUND', ERROR_REQUEST_INVALID);

defined('ERROR_METHOD_NOT_FOUND') || define('ERROR_METHOD_NOT_FOUND', 4);
$errorManager->defineError('ERROR_METHOD_NOT_FOUND', ERROR_REQUEST_INVALID);

defined('ERROR_CLIENT_IS_INVALID') || define('ERROR_CLIENT_IS_INVALID', 5);
$errorManager->defineError('ERROR_CLIENT_IS_INVALID', ERROR_REQUEST_INVALID);

defined('ERROR_PROTOCOL_IS_INVALID') || define('ERROR_PROTOCOL_IS_INVALID', 6);
$errorManager->defineError('ERROR_PROTOCOL_IS_INVALID', ERROR_REQUEST_INVALID);

defined('ERROR_PERMISSION_DENIED') || define('ERROR_PERMISSION_DENIED', 7);
$errorManager->defineError('ERROR_PERMISSION_DENIED');

defined('ERROR_BAD_VERSION') || define('ERROR_BAD_VERSION', 8);
$errorManager->defineError('ERROR_BAD_VERSION');

defined('ERROR_API_UNAVAILABLE') || define('ERROR_API_UNAVAILABLE', 9);
$errorManager->defineError('ERROR_API_UNAVAILABLE', ERROR_INTERNAL_ERROR);

defined('ERROR_AMAZON_ERROR') || define('ERROR_AMAZON_ERROR', 16);
$errorManager->defineError('ERROR_AMAZON_ERROR', ERROR_INTERNAL_ERROR);

defined('ERROR_AUTH_TOKEN_EXPIRED') || define('ERROR_AUTH_TOKEN_EXPIRED', 19);
$errorManager->defineError('ERROR_AUTH_TOKEN_EXPIRED', ERROR_PERMISSION_DENIED);

defined('ERROR_BAD_FIELD') || define('ERROR_BAD_FIELD', 16029);
$errorManager->defineError('ERROR_BAD_FIELD', ERROR_REQUEST_INVALID);

defined('ERROR_INVALID_PARAM') || define('ERROR_INVALID_PARAM', 16100);
$errorManager->defineError('ERROR_INVALID_PARAM');

defined('ERROR_INVALID_PARAM_STRING') || define('ERROR_INVALID_PARAM_STRING', 16101);
$errorManager->defineError('ERROR_INVALID_PARAM_STRING', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_EMAIL') || define('ERROR_INVALID_PARAM_EMAIL', 16102);
$errorManager->defineError('ERROR_INVALID_PARAM_EMAIL', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_INT') || define('ERROR_INVALID_PARAM_INT', 16103);
$errorManager->defineError('ERROR_INVALID_PARAM_INT', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_CHOICE') || define('ERROR_INVALID_PARAM_CHOICE', 16104);
$errorManager->defineError('ERROR_INVALID_PARAM_CHOICE', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_DATETIME') || define('ERROR_INVALID_PARAM_DATETIME', 16105);
$errorManager->defineError('ERROR_INVALID_PARAM_DATETIME', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_OBJECT') || define('ERROR_INVALID_PARAM_OBJECT', 16106);
$errorManager->defineError('ERROR_INVALID_PARAM_OBJECT', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_NULL') || define('ERROR_INVALID_PARAM_NULL', 16107);
$errorManager->defineError('ERROR_INVALID_PARAM_NULL', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_LENGTH') || define('ERROR_INVALID_PARAM_LENGTH', 16108);
$errorManager->defineError('ERROR_INVALID_PARAM_LENGTH', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_NOT_NULL') || define('ERROR_INVALID_PARAM_NOT_NULL', 16109);
$errorManager->defineError('ERROR_INVALID_PARAM_NOT_NULL', ERROR_INVALID_PARAM);

defined('ERROR_MISSING_PARAM') || define('ERROR_MISSING_PARAM', 16110);
$errorManager->defineError('ERROR_MISSING_PARAM', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_FLOAT') || define('ERROR_INVALID_PARAM_FLOAT', 16111);
$errorManager->defineError('ERROR_INVALID_PARAM_FLOAT', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_HEXA') || define('ERROR_INVALID_PARAM_HEXA', 16112);
$errorManager->defineError('ERROR_INVALID_PARAM_HEXA', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_REGEX') || define('ERROR_INVALID_PARAM_REGEX', 16113);
$errorManager->defineError('ERROR_INVALID_PARAM_REGEX', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_BUCKET') || define('ERROR_INVALID_PARAM_BUCKET', 16114);
$errorManager->defineError('ERROR_INVALID_PARAM_BUCKET', ERROR_INVALID_PARAM);

defined('ERROR_INVALID_PARAM_DECIMAL') || define('ERROR_INVALID_PARAM_DECIMAL', 16116);
$errorManager->defineError('ERROR_INVALID_PARAM_DECIMAL', ERROR_INVALID_PARAM);

defined('ERROR_COMPANY_NOT_FOUND') || define('ERROR_COMPANY_NOT_FOUND', 16201);
$errorManager->defineError('ERROR_COMPANY_NOT_FOUND');

defined('ERROR_USER_NOT_FOUND') || define('ERROR_USER_NOT_FOUND', 16301);
$errorManager->defineError('ERROR_USER_NOT_FOUND');

defined('ERROR_CREDENTIAL_ALREADY_EXIST') || define('ERROR_CREDENTIAL_ALREADY_EXIST', 16302);
$errorManager->defineError('ERROR_CREDENTIAL_ALREADY_EXIST');
// "ce login est déjà utilisé", 'this login is already used'
defined('ERROR_ACCOUNT_ALREADY_CONFIRMED') || define('ERROR_ACCOUNT_ALREADY_CONFIRMED', 16304);
$errorManager->defineError('ERROR_ACCOUNT_ALREADY_CONFIRMED');

defined('ERROR_IPAD_ALREADY_CONNECTED') || define('ERROR_IPAD_ALREADY_CONNECTED', 16305);
$errorManager->defineError('ERROR_IPAD_ALREADY_CONNECTED');

defined('ERROR_PRODUCT_NOT_FOUND') || define('ERROR_PRODUCT_NOT_FOUND', 16306);
$errorManager->defineError('ERROR_PRODUCT_NOT_FOUND');

defined('ERROR_LOGIN_WITH_OLD_PLAN_WITHOUT_LICENSE') || define('ERROR_LOGIN_WITH_OLD_PLAN_WITHOUT_LICENSE', 16307);
$errorManager->defineError('ERROR_LOGIN_WITH_OLD_PLAN_WITHOUT_LICENSE');

defined('ERROR_PROJECT_NOT_FOUND') || define('ERROR_PROJECT_NOT_FOUND', 16308);
$errorManager->defineError('ERROR_PROJECT_NOT_FOUND');

defined('ERROR_PROJECT_PARTICIPANT_NOT_FOUND') || define('ERROR_PROJECT_PARTICIPANT_NOT_FOUND', 16309);
$errorManager->defineError('ERROR_PROJECT_PARTICIPANT_NOT_FOUND');

defined('ERROR_HAVE_THIS_RECURRING_PRODUCT') || define('ERROR_HAVE_THIS_RECURRING_PRODUCT', 16310);
$errorManager->defineError('ERROR_HAVE_THIS_RECURRING_PRODUCT');

defined('ERROR_WITH_STRIPE') || define('ERROR_WITH_STRIPE', 16311);
$errorManager->defineError('ERROR_WITH_STRIPE');

defined('ERROR_EMAIL_MUST_BE_CONFIRMED') || define('ERROR_EMAIL_MUST_BE_CONFIRMED', 16313);
$errorManager->defineError('ERROR_EMAIL_MUST_BE_CONFIRMED');

defined('ERROR_CANNOT_ACTIVATE_TRIAL_ALREADY_HAVE_PREMIUM') || define('ERROR_CANNOT_ACTIVATE_TRIAL_ALREADY_HAVE_PREMIUM', 16314);
$errorManager->defineError('ERROR_CANNOT_ACTIVATE_TRIAL_ALREADY_HAVE_PREMIUM');

defined('ERROR_CANNOT_ACTIVATE_TRIAL_ALREADY_HAD_OFFER') || define('ERROR_CANNOT_ACTIVATE_TRIAL_ALREADY_HAD_OFFER', 16315);
$errorManager->defineError('ERROR_CANNOT_ACTIVATE_TRIAL_ALREADY_HAD_OFFER');

defined('ERROR_SHARED_REPORT_NOT_FOUND') || define('ERROR_SHARED_REPORT_NOT_FOUND', 1002);
$errorManager->defineError('ERROR_SHARED_REPORT_NOT_FOUND');

defined('ERROR_SHARED_REPORT_INVALID_PASSWORD') || define('ERROR_SHARED_REPORT_INVALID_PASSWORD', 16318);
$errorManager->defineError('ERROR_SHARED_REPORT_INVALID_PASSWORD');

defined('ERROR_PROJECT_TEMPLATE_NOT_FOUND') || define('ERROR_PROJECT_TEMPLATE_NOT_FOUND', 16319);
$errorManager->defineError('ERROR_PROJECT_TEMPLATE_NOT_FOUND');

defined('ERROR_PROJECT_TEMPLATE_ALREADY_EXISTS') || define('ERROR_PROJECT_TEMPLATE_ALREADY_EXISTS', 16320);
$errorManager->defineError('ERROR_PROJECT_TEMPLATE_ALREADY_EXISTS');
