<?php

namespace DoctrineProxies\__CG__\Core\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Payment extends \Core\Model\Payment implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'id', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'type', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'receiptData', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'amount', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'currency', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'timestamp', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'txnId', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'externalid', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'vat', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'shipping');
        }

        return array('__isInitialized__', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'id', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'type', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'receiptData', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'amount', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'currency', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'timestamp', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'txnId', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'externalid', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'vat', '' . "\0" . 'Core\\Model\\Payment' . "\0" . 'shipping');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Payment $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setReceiptData($receiptData)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReceiptData', array($receiptData));

        return parent::setReceiptData($receiptData);
    }

    /**
     * {@inheritDoc}
     */
    public function getReceiptData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReceiptData', array());

        return parent::getReceiptData();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', array($amount));

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', array());

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp($timestamp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', array($timestamp));

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', array());

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setTxnId($txnId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTxnId', array($txnId));

        return parent::setTxnId($txnId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTxnId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTxnId', array());

        return parent::getTxnId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExternalid($externalid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExternalid', array($externalid));

        return parent::setExternalid($externalid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExternalid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExternalid', array());

        return parent::getExternalid();
    }

    /**
     * {@inheritDoc}
     */
    public function setVat($vat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVat', array($vat));

        return parent::setVat($vat);
    }

    /**
     * {@inheritDoc}
     */
    public function getVat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVat', array());

        return parent::getVat();
    }

    /**
     * {@inheritDoc}
     */
    public function setShipping($shipping)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShipping', array($shipping));

        return parent::setShipping($shipping);
    }

    /**
     * {@inheritDoc}
     */
    public function getShipping()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShipping', array());

        return parent::getShipping();
    }

}
