<?php

namespace DoctrineProxies\__CG__\Core\Model;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class SharedReport extends \Core\Model\SharedReport implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'id', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'reportid', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'projectid', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'projectname', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'hash', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'password', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'timestamp', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'user', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'company');
        }

        return array('__isInitialized__', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'id', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'reportid', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'projectid', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'projectname', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'hash', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'password', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'timestamp', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'user', '' . "\0" . 'Core\\Model\\SharedReport' . "\0" . 'company');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (SharedReport $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportid($reportid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportid', array($reportid));

        return parent::setReportid($reportid);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportid', array());

        return parent::getReportid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectid($projectid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectid', array($projectid));

        return parent::setProjectid($projectid);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectid', array());

        return parent::getProjectid();
    }

    /**
     * {@inheritDoc}
     */
    public function setProjectname($projectname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjectname', array($projectname));

        return parent::setProjectname($projectname);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjectname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjectname', array());

        return parent::getProjectname();
    }

    /**
     * {@inheritDoc}
     */
    public function setHash($hash)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHash', array($hash));

        return parent::setHash($hash);
    }

    /**
     * {@inheritDoc}
     */
    public function getHash()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHash', array());

        return parent::getHash();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimestamp($timestamp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimestamp', array($timestamp));

        return parent::setTimestamp($timestamp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimestamp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimestamp', array());

        return parent::getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Core\Model\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany(\Core\Model\Company $company)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', array($company));

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', array());

        return parent::getCompany();
    }

}
